jobs:
  dastardly:
    name: Scan with Dastardly
    # You may pin to the exact commit or the version.
    # uses: PortSwigger/dastardly-github-action@f72f38f8b4ac8ed59c69854cc77eb9d53e50e78b
    runs-on: ubuntu-latest
    steps:
      - name: Run Dastardly Action Step
        continue-on-error: true                        # This allows subsequent steps to run even if this step fails
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'https://ginandjuice.shop'
          output-filename: 'dastardly-report.xml'

on: workflow_dispatch
